DATASET:
  root_dataset: "./data/"
  list_train: "./data/training.odgt"
  list_val: "./data/validation.odgt"
  num_class: 2
  imgSizes: (300, 375, 450, 525, 600)
  imgMaxSize: 180
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1_deepsup"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 16
  num_epoch: 1
  start_epoch: 0
  epoch_iters: 2000
  optim: "SGD"
  lr_encoder: 0.004
  lr_decoder: 0.004
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.8
  fix_bn: False
  workers: 16
  disp_iter: 50
  seed: 304
  max_iters: 10000

VAL:
  visualize: True
  checkpoint: "epoch_1.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/ade20k-mobilenetv2dilated-c1_deepsup"
